#!/bin/bash

ask_what_to_do () {
	echo "Continue? y/n"
	read ans
	if [[ $ans == "n" ]]
	then
		exit 0
	fi
}

echo "make clean ... "
make clean

if [[ $? != 0 ]]
then 
	ask_what_to_do
fi

echo "make ..."
make

if  [[ $? != 0 ]] 
then	
	ask_what_to_do
fi

echo "executing test ..."
./test

if [[ $? != 0 ]]
then
	ask_what_to_do
fi

echo "checking coverage ..."
gcov list.c

if [[ $? != 0 ]]
then
        ask_what_to_do
fi
