#!/bin/bash

echo "make clean ... "
make clean

if [[ $? != 0 ]]
then 
	exit $?
fi

echo "make ..."
make

if  [[ $? != 0 ]] 
then	
	exit $?
fi

echo "executing test ..."
./test

if [[ $? != 0 ]]
then
	exit $?
fi

echo "checking coverage ..."
gcov list.c

if [[ $? != 0 ]]
then
        exit $?
fi

/usr/local/bin/gcovr -r ./ -p
